apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  replicas: 3
  selector:
    name: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        name: tomcat
    spec:
      containers:
      - name: tomcat
        image: ivanbrazza/tomcat-demo
        ports:
        - containerPort: 8080
